// Icon mapping system for Server/Client Component serialization
// This allows us to pass icon keys from Server Components to Client Components

import { 
  Home, 
  FileText, 
  FolderOpen, 
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  BarChart3,
  Users,
  Clock,
  Plus,
  Settings,
  User,
  Search,
  Bell,
  Menu,
  X,
  Edit,
  Trash2,
  Save,
  Download,
  Upload,
  Eye,
  EyeOff,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Star,
  Heart,
  Share,
  Copy,
  ExternalLink,
  Calendar,
  Filter,
  Grid,
  List,
  Bookmark,
  Tag,
  Flag,
  Mail,
  Phone,
  MapPin,
  Globe,
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  Key,
  Database,
  Server,
  Cloud,
  Wifi,
  WifiOff,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Maximize,
  Minimize,
  RotateCcw,
  RotateCw,
  ZoomIn,
  ZoomOut,
  Move,
  Image,
  Video,
  Music,
  Headphones,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Power,
  PowerOff,
  RefreshCw,
  Scissors,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardX,
  BookOpen,
  Book,
  Library,
  GraduationCap,
  Award,
  Trophy,
  Target,
  Package,
  Box,
  Archive,
  Inbox,
  Send,
  MessageSquare,
  MessageCircle,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Crown,
  Briefcase,
  Building,
  Store,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Activity,
  PieChart,
  BarChart,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  Umbrella,
  Wind,
  Compass,
  Navigation,
  Map,
  Car,
  Leaf,
  Flower,
  Coffee,
  Wine,
  Gift,
  Sparkles,
  Palette,
  Brush,
  Pen,
  Pencil,
  PenTool,
  Eraser,
  Ruler,
  Paperclip,
  Link,
  Unlink,
  Anchor,
  Feather,
  Gem,
  Wallet,
  Receipt,
  Calculator,
  Verified,
  BadgeCheck,
  Ticket,
  QrCode,
  Barcode,
  Hash,
  AtSign,
  Percent,
  Minus,
  Equal,
  Infinity
} from 'lucide-react'

// Icon mapping object
export const ICON_MAP = {
  // Navigation
  home: Home,
  'file-text': FileText,
  'folder-open': FolderOpen,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  
  // Stats and Analytics
  'bar-chart-3': BarChart3,
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  activity: Activity,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  
  // Users and People
  users: Users,
  user: User,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-check': UserCheck,
  'user-x': UserX,
  crown: Crown,
  
  // Time and Calendar
  clock: Clock,
  calendar: Calendar,
  
  // Actions
  plus: Plus,
  edit: Edit,
  'trash-2': Trash2,
  save: Save,
  download: Download,
  upload: Upload,
  copy: Copy,
  share: Share,
  search: Search,
  filter: Filter,
  
  // UI Elements
  menu: Menu,
  x: X,
  settings: Settings,
  bell: Bell,
  eye: Eye,
  'eye-off': EyeOff,
  grid: Grid,
  list: List,
  
  // Status and Feedback
  check: Check,
  'alert-circle': AlertCircle,
  info: Info,
  'help-circle': HelpCircle,
  star: Star,
  heart: Heart,
  flag: Flag,
  bookmark: Bookmark,
  tag: Tag,
  
  // Communication
  mail: Mail,
  phone: Phone,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  send: Send,
  
  // Location
  'map-pin': MapPin,
  globe: Globe,
  map: Map,
  compass: Compass,
  navigation: Navigation,
  
  // Security
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'shield-x': ShieldX,
  key: Key,
  verified: Verified,
  'badge-check': BadgeCheck,
  
  // Technology
  database: Database,
  server: Server,
  cloud: Cloud,
  wifi: Wifi,
  'wifi-off': WifiOff,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  
  // Media
  play: Play,
  pause: Pause,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  repeat: Repeat,
  shuffle: Shuffle,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  headphones: Headphones,
  mic: Mic,
  'mic-off': MicOff,
  camera: Camera,
  'camera-off': CameraOff,
  image: Image,
  video: Video,
  music: Music,
  
  // Tools
  brush: Brush,
  pen: Pen,
  pencil: Pencil,
  'pen-tool': PenTool,
  eraser: Eraser,
  ruler: Ruler,
  scissors: Scissors,
  paperclip: Paperclip,
  
  // Business
  briefcase: Briefcase,
  building: Building,
  store: Store,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  wallet: Wallet,
  receipt: Receipt,
  calculator: Calculator,
  
  // Education
  'book-open': BookOpen,
  book: Book,
  library: Library,
  'graduation-cap': GraduationCap,
  award: Award,
  trophy: Trophy,
  target: Target,
  
  // Nature
  leaf: Leaf,
  flower: Flower,
  sun: Sun,
  moon: Moon,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  umbrella: Umbrella,
  wind: Wind,
  
  // Food and Drink
  coffee: Coffee,
  wine: Wine,
  
  // Celebration
  gift: Gift,
  sparkles: Sparkles,
  
  // Utilities
  power: Power,
  'power-off': PowerOff,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  maximize: Maximize,
  minimize: Minimize,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  move: Move,
  
  // Clipboard
  clipboard: Clipboard,
  'clipboard-check': ClipboardCheck,
  'clipboard-copy': ClipboardCopy,
  'clipboard-list': ClipboardList,
  'clipboard-x': ClipboardX,
  
  // Links
  link: Link,
  unlink: Unlink,
  'external-link': ExternalLink,
  anchor: Anchor,
  
  // Storage
  package: Package,
  box: Box,
  archive: Archive,
  inbox: Inbox,
  
  // Symbols
  hash: Hash,
  'at-sign': AtSign,
  percent: Percent,
  minus: Minus,
  equal: Equal,
  infinity: Infinity,
  
  // Special
  'qr-code': QrCode,
  barcode: Barcode,
  ticket: Ticket,
  gem: Gem,
  feather: Feather,
  palette: Palette,
  car: Car
} as const

// Type for icon keys
export type IconKey = keyof typeof ICON_MAP

// Helper function to get icon component by key
export function getIcon(iconKey: IconKey | string): React.ComponentType<{ className?: string }> | null {
  return ICON_MAP[iconKey as IconKey] || null
}

// Helper function to check if an icon key exists
export function isValidIconKey(iconKey: string): iconKey is IconKey {
  return iconKey in ICON_MAP
}

// Get all available icon keys
export function getAvailableIconKeys(): IconKey[] {
  return Object.keys(ICON_MAP) as IconKey[]
}

// Default icon fallback
export const DEFAULT_ICON = FileText