export const stateEligibilities = {
    "Alabama": {
        "definition": "Speech or language impairment means a communication disorder – such as stuttering, impaired articulation, a language impairment or a voice impairment – that adversely affects a child's educational performance. Speech impairments may involve articulation disorders (errors like substitutions, distortions or omissions), fluency disorders (disruptions in smoothness or rhythm), and voice disorders (atypical pitch, loudness, resonance or quality). Language impairments involve difficulties understanding or using phonology, morphology, syntax, semantics or pragmatics.",
        "eligibility": "Eligibility generally requires (a) meeting the definition of speech or language impairment, (b) an adverse effect on educational performance, and (c) a significant discrepancy from typical communication skills in one or more areas (articulation, fluency, expressive/receptive language, or voice). Evaluations must use culturally and linguistically appropriate instruments and include classroom observations. Some states also require diagnosis by a licensed speech‑language pathologist and certification by the eligibility team.",
        "preschool": "For preschool children (ages 3–5), eligibility may fall under developmental delay when speech or language development—including expressive and receptive language, articulation and fluency—is at least two standard deviations below the national norm or 25% delayed in age equivalency. Teams must base the determination on multiple measures and document that the delay adversely affects daily life and educational performance."
    },
    "Alaska": {
        "definition": "Speech or language impairment means a communication disorder – such as stuttering, impaired articulation, a language impairment or a voice impairment – that adversely affects a child's educational performance. Speech impairments may involve articulation disorders (errors like substitutions, distortions or omissions), fluency disorders (disruptions in smoothness or rhythm), and voice disorders (atypical pitch, loudness, resonance or quality). Language impairments involve difficulties understanding or using phonology, morphology, syntax, semantics or pragmatics.",
        "eligibility": "Eligibility generally requires (a) meeting the definition of speech or language impairment, (b) an adverse effect on educational performance, and (c) a significant discrepancy from typical communication skills in one or more areas (articulation, fluency, expressive/receptive language, or voice). Evaluations must use culturally and linguistically appropriate instruments and include classroom observations. Some states also require diagnosis by a licensed speech‑language pathologist and certification by the eligibility team.",
        "preschool": "For preschool children (ages 3–5), eligibility may fall under developmental delay when speech or language development—including expressive and receptive language, articulation and fluency—is at least two standard deviations below the national norm or 25% delayed in age equivalency. Teams must base the determination on multiple measures and document that the delay adversely affects daily life and educational performance.",
        "state_specific": "Alaska requires a student to exhibit a communication disorder such as stuttering, impaired articulation, language impairment or voice impairment that adversely affects educational performance; need special facilities or methods; be diagnosed by a physician or speech‑language pathologist; and be certified by the eligibility team. For early childhood developmental delay, the student must function at least two standard deviations below the norm (or 25% delayed) in speech or language development—including expressive/receptive language, articulation and fluency—and the delay must adversely affect daily life."
    },
    "Arizona": {
        "definition": "Speech or language impairment means a communication disorder – such as stuttering, impaired articulation, a language impairment or a voice impairment – that adversely affects a child's educational performance. Speech impairments may involve articulation disorders (errors like substitutions, distortions or omissions), fluency disorders (disruptions in smoothness or rhythm), and voice disorders (atypical pitch, loudness, resonance or quality). Language impairments involve difficulties understanding or using phonology, morphology, syntax, semantics or pragmatics.",
        "eligibility": "Eligibility generally requires (a) meeting the definition of speech or language impairment, (b) an adverse effect on educational performance, and (c) a significant discrepancy from typical communication skills in one or more areas (articulation, fluency, expressive/receptive language, or voice). Evaluations must use culturally and linguistically appropriate instruments and include classroom observations. Some states also require diagnosis by a licensed speech‑language pathologist and certification by the eligibility team.",
        "preschool": "For preschool children (ages 3–5), eligibility may fall under developmental delay when speech or language development—including expressive and receptive language, articulation and fluency—is at least two standard deviations below the national norm or 25% delayed in age equivalency. Teams must base the determination on multiple measures and document that the delay adversely affects daily life and educational performance."
    },
    "Arkansas": {
        "definition": "Speech or language impairment means a communication disorder – such as stuttering, impaired articulation, a language impairment or a voice impairment – that adversely affects a child's educational performance. Speech impairments may involve articulation disorders (errors like substitutions, distortions or omissions), fluency disorders (disruptions in smoothness or rhythm), and voice disorders (atypical pitch, loudness, resonance or quality). Language impairments involve difficulties understanding or using phonology, morphology, syntax, semantics or pragmatics.",
        "eligibility": "Eligibility generally requires (a) meeting the definition of speech or language impairment, (b) an adverse effect on educational performance, and (c) a significant discrepancy from typical communication skills in one or more areas (articulation, fluency, expressive/receptive language, or voice). Evaluations must use culturally and linguistically appropriate instruments and include classroom observations. Some states also require diagnosis by a licensed speech‑language pathologist and certification by the eligibility team.",
        "preschool": "For preschool children (ages 3–5), eligibility may fall under developmental delay when speech or language development—including expressive and receptive language, articulation and fluency—is at least two standard deviations below the national norm or 25% delayed in age equivalency. Teams must base the determination on multiple measures and document that the delay adversely affects daily life and educational performance."
    },
    "California": {
        "definition": "Speech or language impairment means a communication disorder – such as stuttering, impaired articulation, a language impairment or a voice impairment – that adversely affects a child's educational performance. Speech impairments may involve articulation disorders (errors like substitutions, distortions or omissions), fluency disorders (disruptions in smoothness or rhythm), and voice disorders (atypical pitch, loudness, resonance or quality). Language impairments involve difficulties understanding or using phonology, morphology, syntax, semantics or pragmatics.",
        "eligibility": "Eligibility generally requires (a) meeting the definition of speech or language impairment, (b) an adverse effect on educational performance, and (c) a significant discrepancy from typical communication skills in one or more areas (articulation, fluency, expressive/receptive language, or voice). Evaluations must use culturally and linguistically appropriate instruments and include classroom observations. Some states also require diagnosis by a licensed speech‑language pathologist and certification by the eligibility team.",
        "preschool": "For preschool children (ages 3–5), eligibility may fall under developmental delay when speech or language development—including expressive and receptive language, articulation and fluency—is at least two standard deviations below the national norm or 25% delayed in age equivalency. Teams must base the determination on multiple measures and document that the delay adversely affects daily life and educational performance.",
        "state_specific": "California's Education Code (5 CCR §3030(b)(11)) lists specific eligibility criteria: a student may qualify if they have an articulation disorder that reduces intelligibility and significantly interferes with communication; a persistent abnormal voice quality, pitch or loudness; a fluency disorder affecting rate and rhythm; or a language disorder evidenced by standardized test scores 1.5 standard deviations below the mean in morphology, syntax, semantics or pragmatics, along with analysis of a language sample. Hearing loss resulting in a language or speech disorder is also considered."
    },
    "Colorado": {
        "definition": "Speech or language impairment means a communication disorder – such as stuttering, impaired articulation, a language impairment or a voice impairment – that adversely affects a child's educational performance. Speech impairments may involve articulation disorders (errors like substitutions, distortions or omissions), fluency disorders (disruptions in smoothness or rhythm), and voice disorders (atypical pitch, loudness, resonance or quality). Language impairments involve difficulties understanding or using phonology, morphology, syntax, semantics or pragmatics.",
        "eligibility": "Eligibility generally requires (a) meeting the definition of speech or language impairment, (b) an adverse effect on educational performance, and (c) a significant discrepancy from typical communication skills in one or more areas (articulation, fluency, expressive/receptive language, or voice). Evaluations must use culturally and linguistically appropriate instruments and include classroom observations. Some states also require diagnosis by a licensed speech‑language pathologist and certification by the eligibility team.",
        "preschool": "For preschool children (ages 3–5), eligibility may fall under developmental delay when speech or language development—including expressive and receptive language, articulation and fluency—is at least two standard deviations below the national norm or 25% delayed in age equivalency. Teams must base the determination on multiple measures and document that the delay adversely affects daily life and educational performance."
    },
    "Connecticut": {
        "definition": "Speech or language impairment means a communication disorder – such as stuttering, impaired articulation, a language impairment or a voice impairment – that adversely affects a child's educational performance. Speech impairments may involve articulation disorders (errors like substitutions, distortions or omissions), fluency disorders (disruptions in smoothness or rhythm), and voice disorders (atypical pitch, loudness, resonance or quality). Language impairments involve difficulties understanding or using phonology, morphology, syntax, semantics or pragmatics.",
        "eligibility": "Eligibility generally requires (a) meeting the definition of speech or language impairment, (b) an adverse effect on educational performance, and (c) a significant discrepancy from typical communication skills in one or more areas (articulation, fluency, expressive/receptive language, or voice). Evaluations must use culturally and linguistically appropriate instruments and include classroom observations. Some states also require diagnosis by a licensed speech‑language pathologist and certification by the eligibility team.",
        "preschool": "For preschool children (ages 3–5), eligibility may fall under developmental delay when speech or language development—including expressive and receptive language, articulation and fluency—is at least two standard deviations below the national norm or 25% delayed in age equivalency. Teams must base the determination on multiple measures and document that the delay adversely affects daily life and educational performance."
    },
    "Delaware": {
        "definition": "Speech or language impairment means a communication disorder – such as stuttering, impaired articulation, a language impairment or a voice impairment – that adversely affects a child's educational performance. Speech impairments may involve articulation disorders (errors like substitutions, distortions or omissions), fluency disorders (disruptions in smoothness or rhythm), and voice disorders (atypical pitch, loudness, resonance or quality). Language impairments involve difficulties understanding or using phonology, morphology, syntax, semantics or pragmatics.",
        "eligibility": "Eligibility generally requires (a) meeting the definition of speech or language impairment, (b) an adverse effect on educational performance, and (c) a significant discrepancy from typical communication skills in one or more areas (articulation, fluency, expressive/receptive language, or voice). Evaluations must use culturally and linguistically appropriate instruments and include classroom observations. Some states also require diagnosis by a licensed speech‑language pathologist and certification by the eligibility team.",
        "preschool": "For preschool children (ages 3–5), eligibility may fall under developmental delay when speech or language development—including expressive and receptive language, articulation and fluency—is at least two standard deviations below the national norm or 25% delayed in age equivalency. Teams must base the determination on multiple measures and document that the delay adversely affects daily life and educational performance.",
        "state_specific": "Delaware's administrative code states that eligibility under the speech‑language classification may be based on an evaluation by a licensed speech‑language pathologist identifying an articulation disorder, language disorder, dysfluent speech or voice disorder. Eligibility begins at age 5, and services may continue until the student receives a high‑school diploma or turns 21."
    },
    "Florida": {
        "definition": "Speech or language impairment means a communication disorder – such as stuttering, impaired articulation, a language impairment or a voice impairment – that adversely affects a child's educational performance. Speech impairments may involve articulation disorders (errors like substitutions, distortions or omissions), fluency disorders (disruptions in smoothness or rhythm), and voice disorders (atypical pitch, loudness, resonance or quality). Language impairments involve difficulties understanding or using phonology, morphology, syntax, semantics or pragmatics.",
        "eligibility": "Eligibility generally requires (a) meeting the definition of speech or language impairment, (b) an adverse effect on educational performance, and (c) a significant discrepancy from typical communication skills in one or more areas (articulation, fluency, expressive/receptive language, or voice). Evaluations must use culturally and linguistically appropriate instruments and include classroom observations. Some states also require diagnosis by a licensed speech‑language pathologist and certification by the eligibility team.",
        "preschool": "For preschool children (ages 3–5), eligibility may fall under developmental delay when speech or language development—including expressive and receptive language, articulation and fluency—is at least two standard deviations below the national norm or 25% delayed in age equivalency. Teams must base the determination on multiple measures and document that the delay adversely affects daily life and educational performance.",
        "state_specific": "Florida defines speech impairments as disorders of speech sounds (phonological or articulation), fluency or voice that interfere with communication, adversely affect educational performance and result in the need for exceptional student education. Language impairments are disorders of phonology, morphology, syntax, semantics or pragmatics that interfere with communication and adversely affect learning; these disorders are not primarily due to age, culture, ethnicity or limited English proficiency."
    },
    "Georgia": {
        "definition": "Speech or language impairment means a communication disorder – such as stuttering, impaired articulation, a language impairment or a voice impairment – that adversely affects a child's educational performance. Speech impairments may involve articulation disorders (errors like substitutions, distortions or omissions), fluency disorders (disruptions in smoothness or rhythm), and voice disorders (atypical pitch, loudness, resonance or quality). Language impairments involve difficulties understanding or using phonology, morphology, syntax, semantics or pragmatics.",
        "eligibility": "Eligibility generally requires (a) meeting the definition of speech or language impairment, (b) an adverse effect on educational performance, and (c) a significant discrepancy from typical communication skills in one or more areas (articulation, fluency, expressive/receptive language, or voice). Evaluations must use culturally and linguistically appropriate instruments and include classroom observations. Some states also require diagnosis by a licensed speech‑language pathologist and certification by the eligibility team.",
        "preschool": "For preschool children (ages 3–5), eligibility may fall under developmental delay when speech or language development—including expressive and receptive language, articulation and fluency—is at least two standard deviations below the national norm or 25% delayed in age equivalency. Teams must base the determination on multiple measures and document that the delay adversely affects daily life and educational performance."
    }
} as const;

export type StateEligibilityData = {
    definition: string;
    eligibility: string;
    preschool: string;
    state_specific?: string;
};

export type StateName = keyof typeof stateEligibilities;